### ISSUE TITLE
There is no train.pkl

### ISSUE THREAD

**Issue by XuShiqiang9894** [AGalassi/StructurePrediction18#2]

**Comment by XuShiqiang9894** [comment]
Hello,when I have downloaded cdcp dataset and glove,I try to run this code,but there is no xxxxx.pkl.Could you give me some advice?Thank you very much

**Comment by qzqzzw** [comment]
Hello, Professor, I have this error when I run training.py, how can I solve it?
FileNotFoundError: [Errno 2] No such file or directory: 'Multi-Task Attentive Residual Networks for Argument Mining\\StructurePrediction18\\Datasets\\cdcp_ACL17\\pickles\\new_3\\total.pkl'
@AGalassi

**Comment by AGalassi** [comment]
The original data are not included in this repository. They should be placed in the "dataset" directory, and then processed with the "dataframe_creator" script to obtain the .pkl files.
